# Generated by Django 3.0.1 on 2020-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=120)),
                ('Product_Type', models.CharField(max_length=120)),
                ('Product_Price', models.DecimalField(decimal_places=3, max_digits=20000)),
                ('Product_Description', models.TextField(blank=True)),
                ('Product_Quantity', models.IntegerField()),
            ],
        ),
    ]
