# Generated by Django 3.0 on 2020-01-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=140)),
                ('pdf', models.FileField(null=True, upload_to='file/files')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdf',
        ),
    ]
