# Generated by Django 3.0 on 2020-01-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_files',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
